import * as vscode from "vscode";
import * as path from "path";
import * as fs from "fs";
import { captureSnapshot, detectTechStack } from "./captureService";
import {
  getOrCreateProject,
  getTimeline,
  getLastInterruption,
  buildDocPrompt,
  saveGeneratedDoc,
  markDocReviewed,
  markProjectDone,
} from "./apiClient";
import { runPrompt, NoLanguageModelError } from "./languageModel";
import { scanCodebase, formatScanForPrompt } from "./codebaseScanner";

let projectId: string | null = null;
let saveDebounceTimer: NodeJS.Timeout | null = null;
let blurTimer: NodeJS.Timeout | null = null;

const SAVE_DEBOUNCE_MS = 10 * 60 * 1000; // ~10 min of active edits between autosave snapshots

async function ensureProject(context: vscode.ExtensionContext): Promise<string | null> {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) return null;

  const root = folders[0].uri.fsPath;
  const name = path.basename(root);
  const techStack = detectTechStack(root);

  try {
    const project = await getOrCreateProject(name, root, techStack);
    return project._id;
  } catch (err: any) {
    vscode.window.showErrorMessage(
      `Resume Where You Left Off: couldn't reach the backend (${err.message}). ` +
        `Check resumeWhereYouLeftOff.apiUrl / apiKey in settings.`
    );
    return null;
  }
}

/**
 * Called once on activation. If Overview.md/README.md don't already exist,
 * offers a one-click prompt to generate them from a codebase scan - this is
 * what makes doc generation feel automatic rather than something the
 * developer has to remember to run manually.
 *
 * Deliberately still asks first, rather than silently writing files on
 * every project open - an unprompted file write the first time someone
 * uses this would be a bad surprise. But unlike the manual command flow,
 * accepting here writes directly (no second "write to disk?" prompt) since
 * clicking the button IS the consent.
 */
async function offerAutoGeneration(currentProjectId: string, workspaceRoot: string) {
  const config = vscode.workspace.getConfiguration("resumeWhereYouLeftOff");
  if (!config.get<boolean>("autoGenerateDocsOnOpen", true)) return;

  const overviewExists = fs.existsSync(path.join(workspaceRoot, "Overview.md"));
  const readmeExists = fs.existsSync(path.join(workspaceRoot, "README.md"));

  if (overviewExists && readmeExists) return; // nothing to offer, don't nag

  const missing: ("overview" | "readme")[] = [];
  if (!overviewExists) missing.push("overview");
  if (!readmeExists) missing.push("readme");

  const label = missing.map((m) => (m === "overview" ? "Overview.md" : "README.md")).join(" and ");
  const choice = await vscode.window.showInformationMessage(
    `Resume Where You Left Off: no ${label} found for this project. Generate ${missing.length > 1 ? "them" : "it"} from a scan of your codebase?`,
    `Generate ${label}`,
    "Don't ask again for this project",
    "Not now"
  );

  if (choice === "Don't ask again for this project") {
    await config.update("autoGenerateDocsOnOpen", false, vscode.ConfigurationTarget.Workspace);
    return;
  }
  if (choice !== `Generate ${label}`) return;

  for (const docType of missing) {
    try {
      const doc = await generateCodebaseDoc(currentProjectId, docType);
      if (!doc) continue;

      const fileName = docType === "overview" ? "Overview.md" : "README.md";
      const targetUri = vscode.Uri.file(path.join(workspaceRoot, fileName));
      await vscode.workspace.fs.writeFile(targetUri, Buffer.from(doc.content, "utf-8"));
      await markDocReviewed(doc._id);

      const openedDoc = await vscode.workspace.openTextDocument(targetUri);
      await vscode.window.showTextDocument(openedDoc, { preview: false });
    } catch (err: any) {
      if (err instanceof NoLanguageModelError) {
        const openChoice = await vscode.window.showErrorMessage(err.message, "Open Extensions");
        if (openChoice === "Open Extensions") {
          vscode.commands.executeCommand("workbench.extensions.search", "GitHub Copilot");
        }
        return; // no point trying the second doc type if there's no model at all
      }
      vscode.window.showErrorMessage(`Auto-generation of ${docType} failed: ${err.message}`);
    }
  }
}


function registerAutosaveCapture(context: vscode.ExtensionContext) {
  const disposable = vscode.workspace.onDidSaveTextDocument(() => {
    if (!projectId) return;

    // Debounce: only actually capture once per SAVE_DEBOUNCE_MS window,
    // no matter how many saves happen in between.
    if (saveDebounceTimer) return;

    saveDebounceTimer = setTimeout(() => {
      saveDebounceTimer = null;
    }, SAVE_DEBOUNCE_MS);

    captureSnapshot(projectId, "autosave");
  });

  context.subscriptions.push(disposable);
}

function registerInterruptionCapture(context: vscode.ExtensionContext) {
  const config = vscode.workspace.getConfiguration("resumeWhereYouLeftOff");
  const thresholdMs = config.get<number>("interruptionThresholdSeconds", 60) * 1000;

  const disposable = vscode.window.onDidChangeWindowState((state) => {
    if (!projectId) return;

    if (!state.focused) {
      // Window lost focus - start a timer. If it's still unfocused after
      // the threshold, treat it as a real interruption (not just an
      // Alt-Tab to check something for 5 seconds).
      blurTimer = setTimeout(() => {
        captureSnapshot(projectId!, "interruption");
      }, thresholdMs);
    } else {
      // Regained focus before the threshold - cancel, it wasn't a real interruption.
      if (blurTimer) {
        clearTimeout(blurTimer);
        blurTimer = null;
      }
    }
  });

  context.subscriptions.push(disposable);
}

function registerCommitCapture(context: vscode.ExtensionContext) {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) return;

  const root = folders[0].uri.fsPath;
  // Committing updates the ref file for the current branch - watching this
  // is more reliable than trying to hook the VS Code Git extension API
  // directly, and doesn't depend on the built-in Git extension being active.
  const watcher = vscode.workspace.createFileSystemWatcher(
    new vscode.RelativePattern(root, ".git/refs/heads/**")
  );

  watcher.onDidChange(() => {
    if (!projectId) return;
    captureSnapshot(projectId, "commit");
  });
  watcher.onDidCreate(() => {
    if (!projectId) return;
    captureSnapshot(projectId, "commit");
  });

  context.subscriptions.push(watcher);
}

const CODEBASE_GROUNDING_RULES = `
Grounding rules (do not violate these):
1. Only describe functions, classes, routes, or files that appear in the
   extracted signatures and file tree below - these are real lines pulled
   directly from the source code, not a summary you should embellish.
2. Do not invent the purpose of a function beyond what its name and
   signature suggest. If a function's purpose isn't clear from its name,
   describe it neutrally (e.g. "handles X-related requests") rather than
   guessing specifics.
3. Do not claim the project has features, integrations, or behavior not
   evidenced by the file tree or signatures.
4. If the codebase is small or the signatures are sparse, keep the output
   short rather than padding it with generic filler.
`.trim();

/**
 * Codebase-aware generation - grounds Overview.md/README.md in the ACTUAL
 * source files via codebaseScanner.ts, instead of only session history.
 * This covers the case session-based grounding can't: an existing codebase
 * with little or no captured session history yet.
 */
async function generateCodebaseDoc(currentProjectId: string, docType: "overview" | "readme") {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) {
    vscode.window.showWarningMessage("No workspace folder open to scan.");
    return;
  }
  const workspaceRoot = folders[0].uri.fsPath;
  const projectName = path.basename(workspaceRoot);

  return vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: `Scanning codebase for ${docType}.md...`,
      cancellable: true,
    },
    async (progress, cancellationToken) => {
      progress.report({ message: "Reading source files..." });
      const scan = scanCodebase(workspaceRoot);
      const scanText = formatScanForPrompt(scan);

      const prompt =
        docType === "overview"
          ? `
You are drafting Overview.md for a software project, to be read by a
developer joining the project later.

Project name: ${projectName}

${scanText}

${CODEBASE_GROUNDING_RULES}

Output format - exactly these three headings, in this order:

## Purpose
1-2 sentences on what this project appears to do, inferred only from the
file tree and function/route names above.

## Structure
Bulleted, briefly describing what each major folder/file group appears to
be responsible for, based only on the file tree and signatures above.

## Key Functions & Routes
Bulleted list of the most significant functions, classes, or API routes
found above, with a short (under 10 words) neutral description of each
based on its name/signature - not invented behavior.
`.trim()
          : `
You are writing a standard external-facing README.md for a project's repo.

Project name: ${projectName}

${scanText}

${CODEBASE_GROUNDING_RULES}

Output format - exactly these headings, in this order:

# ${projectName}

One paragraph (2-3 sentences) describing what the project does, inferred
only from the file tree and signatures above.

## Key Features
Bulleted, based only on the routes/functions/files found above.

## Project Structure
A short bulleted list of the main folders and what they contain, based on
the file tree above.

## Status
One line noting this README was auto-drafted from a scan of ${scan.fileSignatures.length}
source file(s) and should be reviewed by a human before publishing.
`.trim();

      progress.report({ message: "Waiting on your AI model..." });
      const content = await runPrompt(prompt, cancellationToken);

      progress.report({ message: "Saving..." });
      // sourceSessionIds is empty here - this doc is grounded in a live
      // codebase scan, not captured sessions, so there's nothing to trace
      // it to on that axis. The prompt itself is the traceable artifact.
      return saveGeneratedDoc(currentProjectId, docType, content, []);
    }
  );
}

/**
 * Orchestrates the full flow: fetch a grounded prompt from the backend,
 * run it through the developer's own AI (vscode.lm), then save the result
 * back. Shown with a progress notification since the AI call can take a
 * few seconds and shouldn't feel like the command silently did nothing.
 */
async function generateDocViaUserAI(currentProjectId: string, docType: string) {
  return vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: `Generating ${docType}.md...`, cancellable: true },
    async (progress, cancellationToken) => {
      progress.report({ message: "Fetching grounded prompt..." });
      const result = await buildDocPrompt(currentProjectId, docType);

      if (result.noNewSessions || !result.prompt) {
        // Expected state, not an error - nothing new since the last
        // generation of this doc type. Don't waste a Copilot call on it.
        return { noNewSessions: true as const, message: result.message };
      }

      progress.report({ message: "Waiting on your AI model..." });
      const content = await runPrompt(result.prompt, cancellationToken);

      progress.report({ message: "Saving..." });
      const doc = await saveGeneratedDoc(currentProjectId, docType, content, result.sourceSessionIds ?? []);
      return { noNewSessions: false as const, doc };
    }
  );
}

/** Shows a generated doc in a diff view against an empty document, so the
 * developer reviews before anything touches disk. Approving writes the
 * file and marks the doc "reviewed" on the backend. */
async function reviewAndMaybeWrite(doc: { _id: string; docType: string; content: string }) {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) return;

  const fileNameMap: Record<string, string> = {
    overview: "Overview.md",
    progress: "Progress.md",
    readme: "README.md",
    summary: "Summary.md",
  };
  const fileName = fileNameMap[doc.docType] ?? `${doc.docType}.md`;

  const untitled = await vscode.workspace.openTextDocument({
    content: doc.content,
    language: "markdown",
  });
  await vscode.window.showTextDocument(untitled, { preview: false });

  const choice = await vscode.window.showInformationMessage(
    `Review the generated ${fileName} in the editor tab. Write it to disk?`,
    "Write to disk",
    "Discard"
  );

  if (choice === "Write to disk") {
    const targetUri = vscode.Uri.file(path.join(folders[0].uri.fsPath, fileName));
    await vscode.workspace.fs.writeFile(targetUri, Buffer.from(doc.content, "utf-8"));
    await markDocReviewed(doc._id);
    vscode.window.showInformationMessage(`${fileName} written.`);
  }
}

function registerCommands(context: vscode.ExtensionContext) {
  context.subscriptions.push(
    vscode.commands.registerCommand("resumeWhereYouLeftOff.restoreLastSession", async () => {
      if (!projectId) return;
      try {
        const session = await getLastInterruption(projectId);
        const ctx = session.cursorContext;
        const message = ctx
          ? `You were in ${path.basename(ctx.file)} around line ${ctx.line}, on branch ${session.branch}.`
          : `Last interruption was on branch ${session.branch} - no cursor context recorded.`;
        vscode.window.showInformationMessage(message);

        if (ctx?.file) {
          const doc = await vscode.workspace.openTextDocument(ctx.file);
          const editor = await vscode.window.showTextDocument(doc);
          const pos = new vscode.Position(Math.max(0, ctx.line - 1), 0);
          editor.selection = new vscode.Selection(pos, pos);
          editor.revealRange(new vscode.Range(pos, pos));
        }
      } catch {
        vscode.window.showInformationMessage("No interruption snapshot found yet.");
      }
    }),

    vscode.commands.registerCommand("resumeWhereYouLeftOff.showTimeline", async () => {
      if (!projectId) return;
      const sessions = await getTimeline(projectId);
      const items = sessions.map((s: any) => ({
        label: `[${s.triggerType}] ${new Date(s.createdAt).toLocaleString()}`,
        description: s.branch,
        detail: s.summary || "(not yet summarized)",
      }));
      await vscode.window.showQuickPick(items, { placeHolder: "Session timeline" });
    }),

    vscode.commands.registerCommand("resumeWhereYouLeftOff.generateDoc", async () => {
      if (!projectId) return;
      const docType = await vscode.window.showQuickPick(["overview", "progress", "readme"], {
        placeHolder: "Which doc do you want to generate?",
      });
      if (!docType) return;

      try {
        const result = await generateDocViaUserAI(projectId, docType);
        if (result.noNewSessions) {
          vscode.window.showInformationMessage(
            result.message ?? `No new activity since your last ${docType}.md update.`
          );
          return;
        }
        await reviewAndMaybeWrite(result.doc);
      } catch (err: any) {
        if (err instanceof NoLanguageModelError) {
          const choice = await vscode.window.showErrorMessage(err.message, "Open Extensions");
          if (choice === "Open Extensions") {
            vscode.commands.executeCommand("workbench.extensions.search", "GitHub Copilot");
          }
        } else {
          vscode.window.showErrorMessage(`Doc generation failed: ${err.message}`);
        }
      }
    }),

    vscode.commands.registerCommand("resumeWhereYouLeftOff.generateCodebaseDoc", async () => {
      if (!projectId) return;
      const choice = await vscode.window.showQuickPick(
        [
          { label: "overview", description: "Overview.md - purpose, structure, key functions" },
          { label: "readme", description: "README.md - external-facing project description" },
        ],
        { placeHolder: "Scan the codebase and generate which doc?" }
      );
      if (!choice) return;

      try {
        const doc = await generateCodebaseDoc(projectId, choice.label as "overview" | "readme");
        if (doc) await reviewAndMaybeWrite(doc);
      } catch (err: any) {
        if (err instanceof NoLanguageModelError) {
          const openChoice = await vscode.window.showErrorMessage(err.message, "Open Extensions");
          if (openChoice === "Open Extensions") {
            vscode.commands.executeCommand("workbench.extensions.search", "GitHub Copilot");
          }
        } else {
          vscode.window.showErrorMessage(`Codebase scan failed: ${err.message}`);
        }
      }
    }),

    vscode.commands.registerCommand("resumeWhereYouLeftOff.markProjectDone", async () => {
      if (!projectId) return;
      const confirm = await vscode.window.showWarningMessage(
        "Mark this project done and generate Summary.md?",
        "Yes",
        "Cancel"
      );
      if (confirm !== "Yes") return;

      try {
        const result = await generateDocViaUserAI(projectId, "summary");
        if (result.noNewSessions) {
          vscode.window.showInformationMessage(
            result.message ?? "No new activity to summarize - nothing to mark done yet."
          );
          return;
        }
        await reviewAndMaybeWrite(result.doc);
        await markProjectDone(projectId);
      } catch (err: any) {
        if (err instanceof NoLanguageModelError) {
          const choice = await vscode.window.showErrorMessage(err.message, "Open Extensions");
          if (choice === "Open Extensions") {
            vscode.commands.executeCommand("workbench.extensions.search", "GitHub Copilot");
          }
        } else {
          vscode.window.showErrorMessage(`Mark-done failed: ${err.message}`);
        }
      }
    })
  );
}

export async function activate(context: vscode.ExtensionContext) {
  projectId = await ensureProject(context);

  if (!projectId) {
    vscode.window.showWarningMessage(
      "Resume Where You Left Off: no workspace folder open, or backend unreachable. Extension is idle."
    );
    return;
  }

  registerAutosaveCapture(context);
  registerInterruptionCapture(context);
  registerCommitCapture(context);
  registerCommands(context);

  console.log("[resumeWhereYouLeftOff] activated for project", projectId);

  const folders = vscode.workspace.workspaceFolders;
  if (folders && folders.length > 0) {
    // Fire-and-forget: don't block activation on this, and don't let a
    // failure here affect the rest of the extension's setup.
    offerAutoGeneration(projectId, folders[0].uri.fsPath).catch((err) =>
      console.error("[resumeWhereYouLeftOff] auto-generation offer failed:", err)
    );
  }
}

export function deactivate() {
  if (saveDebounceTimer) clearTimeout(saveDebounceTimer);
  if (blurTimer) clearTimeout(blurTimer);
}
